### ISSUE TITLE
Does this still work in Blender 3.6?

### ISSUE THREAD

**Issue by AmberElferink** [PetteriAimonen/blender_addons#2]
Dear Petteri,

I tried to run the script in Blender 3.6.
- Select a face
- Press F3 instead of spacebar
- search "triang"
- The only option still there is Triangulate Faces, which is the default blender option.
I have imported the script via add-ons, and checked the checkmark, but it does not seem to show up

It would be a huge help if this still works :)

**Comment by PetteriAimonen** [comment]
@Andrej730 made some changes for Blender 3.x just a few days ago, do you have the newest version?

**Comment by Andrej730** [comment]
@AmberElferink 

1) please check blender version in trianglefill.py you've installed, it should be 3.0.0:
![image](https://github.com/PetteriAimonen/blender_addons/assets/9417531/d239dc8c-6958-4e93-ad65-9802fc5b7daa)

2) check the system console on blender start - are there any erros?

**Comment by AmberElferink** [comment]
Hi @Andrej730 and @PetteriAimonen ,

Thanks for picking this up so quickly.
Yes, the blender version in the python script is 3.0.0. I just installed this when I found out it would not work, and made the issue here, so I don't even have an older version of this project downloaded.

For clarity, I attached a video showing what I mean, maybe I am doing something wrong :)
https://github.com/PetteriAimonen/blender_addons/assets/32518317/750b413d-e6a3-41ae-aa40-ab32dba98cde

And here are two screenshots of the terminal right after the video, and the python script version of the file.
<img width="446" alt="Screenshot 2023-09-09 200335" src="https://github.com/PetteriAimonen/blender_addons/assets/32518317/f06df0bd-ad1e-4c8c-8404-5554fa703af5">
<img width="618" alt="Screenshot 2023-09-09 200414" src="https://github.com/PetteriAimonen/blender_addons/assets/32518317/a006f898-b815-4439-aea1-a7e4110353e3">

**Comment by Andrej730** [comment]
@AmberElferink just installed 3.5.1 and couldn't reproduce this.
Can you please open system console (Window - Toggle System Console) and check it for errors on enabling the addon?

**Comment by Andrej730** [comment]
@AmberElferink 
I've got another idea - can you check wheither you have Developer Extras checked in Blender preferences?

![image](https://github.com/PetteriAimonen/blender_addons/assets/9417531/fc0463bf-64ba-49d3-a37f-5e9b3dbac135)

**Comment by AmberElferink** [comment]
Thanks @Andrej730, I'm currently on holidays until October. I'll try it once I get back :)

**Comment by AmberElferink** [comment]
Thank you so much @Andrej730, I missed having the Developer options enabled!!! I would recommend updating the readme with:
- turning on Developer options in Interface 
- saying F3 instead of space to search now

Thanks so much for your help! It works like a charm :D
